### PR TITLE
Create go.mod and fix go 1.14 compile error

### PR DESCRIPTION
**Pull request by artheus**
Created a go.mod, since Go Modules are now standard practice.

Fixed the Go 1.14 compiler error, which was `uuid.NewV4()` no longer returning an error.

### CODE REVIEW

**Comment by artheus** [comment]
I will revert most of the changes here, and add the NewJob functions in separate files for build tags pre and post the uuin.NewV4 change.

**Comment by artheus** [comment]
I decided to change the uuid library to github.com/google/uuid as it seems like a more stable choice. And the developers of github.com/satori/go.uuid basically told developers to "live with it" after the unannounced breaking change of their library was made. Please see https://github.com/satori/go.uuid/issues/66

**Comment by kuba--** [comment]
@artheus - this project is not longer maintained (mainly because source{d} as company was closed).
So, I suggest to move/close/fork this repo to the new org.

**Comment by artheus** [comment]
Ok. Sorry to hear that.
Will fork.

**Comment by artheus** [comment]
@kuba-- @jfontan @smola @Serabe Please see https://github.com/go-mq/mq and please tell me if there is something you would like for me to change to give you more credit for the work you've put into this.

**Comment by smola** [comment]
@marnovo Maybe we can update README to suggest @artheus fork?

**Pull request closed without merging**
