### PR TITLE
Adds unbuffered mem queue

### PR DESCRIPTION
**Pull request by se7entyse7en**
See context [here](https://github.com/src-d/lookout/issues/485).

### CODE REVIEW

**Comment by se7entyse7en** [comment]
I'm adding @src-d/applications and @jfontan as he's the maintainer as reviewers.

**Comment by se7entyse7en** [comment]
Ok, I've just realized that I can't add reviewers 😅.

**Comment by jfontan** [comment]
@se7entyse7en I cannot add @src-d/applications to reviewers but I've added data retrieval.

**Comment by se7entyse7en** [comment]
I'm closing this as it's no more needed. The discussion is available at the same link of the context.

**Pull request closed without merging**
